### docker-compose.yaml für PostgreSQL

version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9404
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"